### ISSUE TITLE
additional_stats_container is too large

### ISSUE THREAD

**Issue by cyandev** [LeaPhant/skyblock-stats#44]
The additional stats container (which has login information, skill average, etc) is wrongly sized at 1590px and up. Currently it is sized by
```css
#additional_stats_container{
        white-space: normal;
        width: calc(1120px - 150px);
}
```
This is (assumably) calculated by taking the width off the "wrapper" div at 1590px (1120px) and subtracting the 150px of padding on the base stats container given to the skin render. This doesn't account for the 30px padding on the "basic_stats" div leading to the additional stats being too long.

Screenshot of issue:
![image](https://user-images.githubusercontent.com/27857114/80856673-785e4c80-8c11-11ea-8fd0-9dc8dc24fc7f.png)
