### ISSUE TITLE
Scrollbar styling

### ISSUE THREAD

**Issue by nstringham** [LeaPhant/skyblock-stats#74]
In this issue, I will purpose styling the scrollbars on sky.lea.moe

## The Problem

the problem with unstyled scrollbars is that they are white on most browsers which clashes with the dark esthetic of the site.

![image](https://user-images.githubusercontent.com/44071655/94188452-68bcfa00-fe77-11ea-946c-c28b67549ec7.png)

notice how the scrollbars are the same contrast as the text drawing attention away from the content to the scrollbars.

## My Solution

add styling to the scrollbars with [::-webkit-scrollbar](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) and [scrollbar-color](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color)

however ::-webkit-scrollbar also affects mobile which looks weird because that on mobile people expect to have the auto-hide zero-width scrollbar that comes by default.

The solution is to detect whether the scrollbar has a width in javascript when the page first loads and if it does then add the styles.

```javascript
// checks if the scrollbar has a width should be true with desktop style scrollbars
if (window.innerWidth > document.documentElement.clientWidth) {
  document.documentElement.classList.add('style-scrollbar');
} else {
  document.documentElement.classList.remove('style-scrollbar');
}
```
```css
.style-scrollbar *::-webkit-scrollbar-track
{
    border-radius: 12px;
    background-color: #5a595b;
}

.style-scrollbar *::-webkit-scrollbar
{
    scrollbar-color: #a6145d #5a595b;
    width: 12px;
    height: 10px;
}

.style-scrollbar body::-webkit-scrollbar
{
    background-color: #282828;
}

.style-scrollbar *::-webkit-scrollbar-thumb
{
    border-radius: 12px;
    background-color: #a6145d;
}
```
and here is what it looks like.
![image](https://user-images.githubusercontent.com/44071655/94190935-c737a780-fe7a-11ea-8077-b6f2a70941b3.png)
